[
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "<!--e57a25ab6845829454e8d69fc972939a-->\n\nThe following sections might be updated with supplementary metadata relevant to reviewers and maintainers.\n\n<!--021abf342d371248e50ceaed478a90ca-->\n### Reviews\nSee [the guideline](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#code-review) for information on the review process.\n| Type | Reviewers |\n| ---- | --------- |\n| Concept ACK | [TheCharlatan](https://github.com/bitcoin/bitcoin/pull/28253#issuecomment-1674461756) |\n\nIf your review is incorrectly listed, please react with ð to this comment and the bot will ignore it on the next update.\n",
      "created_at" : "2023-08-10T21:57:06Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/28253#issuecomment-1673970765",
      "id" : 1673970765,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28253",
      "node_id" : "IC_kwDOABII585jxsRN",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 1,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 1,
         "total_count" : 2,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1673970765/reactions"
      },
      "updated_at" : "2023-08-11T09:34:25Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1673970765",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/39886733?v=4",
         "events_url" : "https://api.github.com/users/DrahtBot/events{/privacy}",
         "followers_url" : "https://api.github.com/users/DrahtBot/followers",
         "following_url" : "https://api.github.com/users/DrahtBot/following{/other_user}",
         "gists_url" : "https://api.github.com/users/DrahtBot/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/DrahtBot",
         "id" : 39886733,
         "login" : "DrahtBot",
         "node_id" : "MDQ6VXNlcjM5ODg2NzMz",
         "organizations_url" : "https://api.github.com/users/DrahtBot/orgs",
         "received_events_url" : "https://api.github.com/users/DrahtBot/received_events",
         "repos_url" : "https://api.github.com/users/DrahtBot/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/DrahtBot/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/DrahtBot/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/DrahtBot"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Concept ACK",
      "created_at" : "2023-08-11T09:34:23Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/28253#issuecomment-1674461756",
      "id" : 1674461756,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28253",
      "node_id" : "IC_kwDOABII585jzkI8",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1674461756/reactions"
      },
      "updated_at" : "2023-08-11T09:34:23Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1674461756",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/8421793?v=4",
         "events_url" : "https://api.github.com/users/TheCharlatan/events{/privacy}",
         "followers_url" : "https://api.github.com/users/TheCharlatan/followers",
         "following_url" : "https://api.github.com/users/TheCharlatan/following{/other_user}",
         "gists_url" : "https://api.github.com/users/TheCharlatan/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/TheCharlatan",
         "id" : 8421793,
         "login" : "TheCharlatan",
         "node_id" : "MDQ6VXNlcjg0MjE3OTM=",
         "organizations_url" : "https://api.github.com/users/TheCharlatan/orgs",
         "received_events_url" : "https://api.github.com/users/TheCharlatan/received_events",
         "repos_url" : "https://api.github.com/users/TheCharlatan/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/TheCharlatan/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/TheCharlatan/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/TheCharlatan"
      }
   },
   {
      "_links" : {
         "html" : {
            "href" : "https://github.com/bitcoin/bitcoin/pull/28253#discussion_r1294258580"
         },
         "pull_request" : {
            "href" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/28253"
         },
         "self" : {
            "href" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294258580"
         }
      },
      "author_association" : "MEMBER",
      "body" : "Why not append your message to this message?",
      "commit_id" : "2f19be69109ddc0baed8c9d2db0c8de791b5f6ad",
      "created_at" : "2023-08-15T07:01:51Z",
      "diff_hunk" : "@@ -232,6 +232,15 @@ def wait_for_rpc_connection(self):\n         poll_per_s = 4\n         for _ in range(poll_per_s * self.rpc_timeout):\n             if self.process.poll() is not None:\n+                if self.process.returncode != 0:\n+                    # Print any abrupt shutdown error, so it is visible from the console and the\n+                    # user doesn't have to go node by node checking which one failed.\n+                    with open(self.stderr.name, 'r', encoding='utf-8') as err_file:\n+                        print(\"************************\")\n+                        print(f\"'{self.datadir_path.name}' abruptly aborted with error:\\n\")\n+                        print(''.join(line for line in err_file if line.strip() and line[0] != \"*\"))\n+                        print(\"************************\")\n+\n                 raise FailedToStartError(self._node_msg(\n                     'bitcoind exited with status {} during initialization'.format(self.process.returncode)))",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/28253#discussion_r1294258580",
      "id" : 1294258580,
      "line" : 245,
      "node_id" : "PRRC_kwDOABII585NJNGU",
      "original_commit_id" : "2f19be69109ddc0baed8c9d2db0c8de791b5f6ad",
      "original_line" : 245,
      "original_position" : 14,
      "original_start_line" : null,
      "path" : "test/functional/test_framework/test_node.py",
      "position" : 14,
      "pull_request_review_id" : 1578062646,
      "pull_request_url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/28253",
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 1,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 1,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294258580/reactions"
      },
      "side" : "RIGHT",
      "start_line" : null,
      "start_side" : null,
      "subject_type" : "line",
      "updated_at" : "2023-08-15T07:03:06Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294258580",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "_links" : {
         "html" : {
            "href" : "https://github.com/bitcoin/bitcoin/pull/28253#discussion_r1294613398"
         },
         "pull_request" : {
            "href" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/28253"
         },
         "self" : {
            "href" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294613398"
         }
      },
      "author_association" : "MEMBER",
      "body" : "The idea was to separate the stderr output from the exception being thrown here. Mainly to get a more readable print when a crash happens. The `FailedToStartError` exception message appears in-between two long stack traces.\r\n\r\nBut, either way is ok for me.",
      "commit_id" : "2f19be69109ddc0baed8c9d2db0c8de791b5f6ad",
      "created_at" : "2023-08-15T13:41:51Z",
      "diff_hunk" : "@@ -232,6 +232,15 @@ def wait_for_rpc_connection(self):\n         poll_per_s = 4\n         for _ in range(poll_per_s * self.rpc_timeout):\n             if self.process.poll() is not None:\n+                if self.process.returncode != 0:\n+                    # Print any abrupt shutdown error, so it is visible from the console and the\n+                    # user doesn't have to go node by node checking which one failed.\n+                    with open(self.stderr.name, 'r', encoding='utf-8') as err_file:\n+                        print(\"************************\")\n+                        print(f\"'{self.datadir_path.name}' abruptly aborted with error:\\n\")\n+                        print(''.join(line for line in err_file if line.strip() and line[0] != \"*\"))\n+                        print(\"************************\")\n+\n                 raise FailedToStartError(self._node_msg(\n                     'bitcoind exited with status {} during initialization'.format(self.process.returncode)))",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/28253#discussion_r1294613398",
      "id" : 1294613398,
      "in_reply_to_id" : 1294258580,
      "line" : 245,
      "node_id" : "PRRC_kwDOABII585NKjuW",
      "original_commit_id" : "2f19be69109ddc0baed8c9d2db0c8de791b5f6ad",
      "original_line" : 245,
      "original_position" : 14,
      "original_start_line" : null,
      "path" : "test/functional/test_framework/test_node.py",
      "position" : 14,
      "pull_request_review_id" : 1578585402,
      "pull_request_url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/28253",
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294613398/reactions"
      },
      "side" : "RIGHT",
      "start_line" : null,
      "start_side" : null,
      "subject_type" : "line",
      "updated_at" : "2023-08-15T13:42:43Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294613398",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/5377650?v=4",
         "events_url" : "https://api.github.com/users/furszy/events{/privacy}",
         "followers_url" : "https://api.github.com/users/furszy/followers",
         "following_url" : "https://api.github.com/users/furszy/following{/other_user}",
         "gists_url" : "https://api.github.com/users/furszy/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/furszy",
         "id" : 5377650,
         "login" : "furszy",
         "node_id" : "MDQ6VXNlcjUzNzc2NTA=",
         "organizations_url" : "https://api.github.com/users/furszy/orgs",
         "received_events_url" : "https://api.github.com/users/furszy/received_events",
         "repos_url" : "https://api.github.com/users/furszy/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/furszy/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/furszy/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/furszy"
      }
   },
   {
      "_links" : {
         "html" : {
            "href" : "https://github.com/bitcoin/bitcoin/pull/28253#discussion_r1294617879"
         },
         "pull_request" : {
            "href" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/28253"
         },
         "self" : {
            "href" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294617879"
         }
      },
      "author_association" : "MEMBER",
      "body" : "If you want to keep it, it would also be good to show an example output (CI and non-CI) when this is printed in a \"normal\" test (not create_cache)",
      "commit_id" : "2f19be69109ddc0baed8c9d2db0c8de791b5f6ad",
      "created_at" : "2023-08-15T13:45:18Z",
      "diff_hunk" : "@@ -232,6 +232,15 @@ def wait_for_rpc_connection(self):\n         poll_per_s = 4\n         for _ in range(poll_per_s * self.rpc_timeout):\n             if self.process.poll() is not None:\n+                if self.process.returncode != 0:\n+                    # Print any abrupt shutdown error, so it is visible from the console and the\n+                    # user doesn't have to go node by node checking which one failed.\n+                    with open(self.stderr.name, 'r', encoding='utf-8') as err_file:\n+                        print(\"************************\")\n+                        print(f\"'{self.datadir_path.name}' abruptly aborted with error:\\n\")\n+                        print(''.join(line for line in err_file if line.strip() and line[0] != \"*\"))\n+                        print(\"************************\")\n+\n                 raise FailedToStartError(self._node_msg(\n                     'bitcoind exited with status {} during initialization'.format(self.process.returncode)))",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/28253#discussion_r1294617879",
      "id" : 1294617879,
      "in_reply_to_id" : 1294258580,
      "line" : 245,
      "node_id" : "PRRC_kwDOABII585NKk0X",
      "original_commit_id" : "2f19be69109ddc0baed8c9d2db0c8de791b5f6ad",
      "original_line" : 245,
      "original_position" : 14,
      "original_start_line" : null,
      "path" : "test/functional/test_framework/test_node.py",
      "position" : 14,
      "pull_request_review_id" : 1578592103,
      "pull_request_url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/28253",
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294617879/reactions"
      },
      "side" : "RIGHT",
      "start_line" : null,
      "start_side" : null,
      "subject_type" : "line",
      "updated_at" : "2023-08-15T13:45:18Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294617879",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "_links" : {
         "html" : {
            "href" : "https://github.com/bitcoin/bitcoin/pull/28253#discussion_r1294638606"
         },
         "pull_request" : {
            "href" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/28253"
         },
         "self" : {
            "href" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294638606"
         }
      },
      "author_association" : "MEMBER",
      "body" : "Why might the output differ between CI and non-CI runs? The test framework redirect stderr to a file, and this file seems to remain untouched regardless of the execution environment.\r\n\r\nAlso, the `\"normal\" test (not create_cache)` tense isn't clear for me. Does it refer to running an individual test locally?",
      "commit_id" : "2f19be69109ddc0baed8c9d2db0c8de791b5f6ad",
      "created_at" : "2023-08-15T14:02:27Z",
      "diff_hunk" : "@@ -232,6 +232,15 @@ def wait_for_rpc_connection(self):\n         poll_per_s = 4\n         for _ in range(poll_per_s * self.rpc_timeout):\n             if self.process.poll() is not None:\n+                if self.process.returncode != 0:\n+                    # Print any abrupt shutdown error, so it is visible from the console and the\n+                    # user doesn't have to go node by node checking which one failed.\n+                    with open(self.stderr.name, 'r', encoding='utf-8') as err_file:\n+                        print(\"************************\")\n+                        print(f\"'{self.datadir_path.name}' abruptly aborted with error:\\n\")\n+                        print(''.join(line for line in err_file if line.strip() and line[0] != \"*\"))\n+                        print(\"************************\")\n+\n                 raise FailedToStartError(self._node_msg(\n                     'bitcoind exited with status {} during initialization'.format(self.process.returncode)))",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/28253#discussion_r1294638606",
      "id" : 1294638606,
      "in_reply_to_id" : 1294258580,
      "line" : 245,
      "node_id" : "PRRC_kwDOABII585NKp4O",
      "original_commit_id" : "2f19be69109ddc0baed8c9d2db0c8de791b5f6ad",
      "original_line" : 245,
      "original_position" : 14,
      "original_start_line" : null,
      "path" : "test/functional/test_framework/test_node.py",
      "position" : 14,
      "pull_request_review_id" : 1578628427,
      "pull_request_url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/28253",
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294638606/reactions"
      },
      "side" : "RIGHT",
      "start_line" : null,
      "start_side" : null,
      "subject_type" : "line",
      "updated_at" : "2023-08-15T14:13:24Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294638606",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/5377650?v=4",
         "events_url" : "https://api.github.com/users/furszy/events{/privacy}",
         "followers_url" : "https://api.github.com/users/furszy/followers",
         "following_url" : "https://api.github.com/users/furszy/following{/other_user}",
         "gists_url" : "https://api.github.com/users/furszy/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/furszy",
         "id" : 5377650,
         "login" : "furszy",
         "node_id" : "MDQ6VXNlcjUzNzc2NTA=",
         "organizations_url" : "https://api.github.com/users/furszy/orgs",
         "received_events_url" : "https://api.github.com/users/furszy/received_events",
         "repos_url" : "https://api.github.com/users/furszy/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/furszy/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/furszy/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/furszy"
      }
   },
   {
      "_links" : {
         "html" : {
            "href" : "https://github.com/bitcoin/bitcoin/pull/28253#discussion_r1294654358"
         },
         "pull_request" : {
            "href" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/28253"
         },
         "self" : {
            "href" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294654358"
         }
      },
      "author_association" : "MEMBER",
      "body" : "> Why might the output differ between CI and non-CI runs?\r\n\r\nI thought that the test_runner.py may be doing something with stderr, but it looks like it will get printed:\r\n\r\n```py\r\n                print(BOLD[1] + 'stdout:\\n' + BOLD[0] + stdout + '\\n')\r\n                print(BOLD[1] + 'stderr:\\n' + BOLD[0] + stderr + '\\n')\r\n                if combined_logs_len and os.path.isdir(testdir):\r\n                    # Print the final `combinedlogslen` lines of the combined logs\r\n```\r\n\r\n\r\n\r\n> Also, the `\"normal\" test (not create_cache)` tense isn't clear for me. Does it refer to running an individual test locally?\r\n\r\nYes, I mean any test that is not `create_cache.py`.\r\n\r\n\r\n\r\n> Mainly to get a more readable print when a crash happens. The `FailedToStartError` exception message appears in-between two long stack traces.\r\n\r\nLooking at my code block above, it looks like the error message would be easier to spot in the output if it was part of the combined output, as opposed to the python stack trace, no?\r\n\r\nYou can use newlines to aid reading and break long blocks.",
      "commit_id" : "2f19be69109ddc0baed8c9d2db0c8de791b5f6ad",
      "created_at" : "2023-08-15T14:15:18Z",
      "diff_hunk" : "@@ -232,6 +232,15 @@ def wait_for_rpc_connection(self):\n         poll_per_s = 4\n         for _ in range(poll_per_s * self.rpc_timeout):\n             if self.process.poll() is not None:\n+                if self.process.returncode != 0:\n+                    # Print any abrupt shutdown error, so it is visible from the console and the\n+                    # user doesn't have to go node by node checking which one failed.\n+                    with open(self.stderr.name, 'r', encoding='utf-8') as err_file:\n+                        print(\"************************\")\n+                        print(f\"'{self.datadir_path.name}' abruptly aborted with error:\\n\")\n+                        print(''.join(line for line in err_file if line.strip() and line[0] != \"*\"))\n+                        print(\"************************\")\n+\n                 raise FailedToStartError(self._node_msg(\n                     'bitcoind exited with status {} during initialization'.format(self.process.returncode)))",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/28253#discussion_r1294654358",
      "id" : 1294654358,
      "in_reply_to_id" : 1294258580,
      "line" : 245,
      "node_id" : "PRRC_kwDOABII585NKtuW",
      "original_commit_id" : "2f19be69109ddc0baed8c9d2db0c8de791b5f6ad",
      "original_line" : 245,
      "original_position" : 14,
      "original_start_line" : null,
      "path" : "test/functional/test_framework/test_node.py",
      "position" : 14,
      "pull_request_review_id" : 1578653039,
      "pull_request_url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/28253",
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294654358/reactions"
      },
      "side" : "RIGHT",
      "start_line" : null,
      "start_side" : null,
      "subject_type" : "line",
      "updated_at" : "2023-08-15T14:15:19Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294654358",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "_links" : {
         "html" : {
            "href" : "https://github.com/bitcoin/bitcoin/pull/28253#discussion_r1294678025"
         },
         "pull_request" : {
            "href" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/28253"
         },
         "self" : {
            "href" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294678025"
         }
      },
      "author_association" : "MEMBER",
      "body" : "> > Why might the output differ between CI and non-CI runs?\r\n> \r\n> I thought that the test_runner.py may be doing something with stderr, but it looks like it will get printed:\r\n> \r\n> ```python\r\n>                 print(BOLD[1] + 'stdout:\\n' + BOLD[0] + stdout + '\\n')\r\n>                 print(BOLD[1] + 'stderr:\\n' + BOLD[0] + stderr + '\\n')\r\n>                 if combined_logs_len and os.path.isdir(testdir):\r\n>                     # Print the final `combinedlogslen` lines of the combined logs\r\n> ```\r\n\r\nIn a first glance, that doesn't seems to print the nodes' stderr. That seems to be related to the job stderr (the test run in a subprocess). And those aren't connected.\r\n\r\n>  > Also, the `\"normal\" test (not create_cache)` tense isn't clear for me. Does it refer to running an individual test locally?\r\n> \r\n> Yes, I mean any test that is not `create_cache.py`.\r\n\r\nOk. The result is pretty much the same. Just the stack trace is a bit longer.\r\n\r\n> > Mainly to get a more readable print when a crash happens. The `FailedToStartError` exception message appears in-between two long stack traces.\r\n> \r\n> Looking at my code block above, it looks like the error message would be easier to spot in the output if it was part of the combined output, as opposed to the python stack trace, no?\r\n> \r\n> You can use newlines to aid reading and break long blocks.\r\n\r\nAs far as I can see, we don't support combined output on single test cases. So, that would make us lose the crash cause on individual test runs?",
      "commit_id" : "2f19be69109ddc0baed8c9d2db0c8de791b5f6ad",
      "created_at" : "2023-08-15T14:32:46Z",
      "diff_hunk" : "@@ -232,6 +232,15 @@ def wait_for_rpc_connection(self):\n         poll_per_s = 4\n         for _ in range(poll_per_s * self.rpc_timeout):\n             if self.process.poll() is not None:\n+                if self.process.returncode != 0:\n+                    # Print any abrupt shutdown error, so it is visible from the console and the\n+                    # user doesn't have to go node by node checking which one failed.\n+                    with open(self.stderr.name, 'r', encoding='utf-8') as err_file:\n+                        print(\"************************\")\n+                        print(f\"'{self.datadir_path.name}' abruptly aborted with error:\\n\")\n+                        print(''.join(line for line in err_file if line.strip() and line[0] != \"*\"))\n+                        print(\"************************\")\n+\n                 raise FailedToStartError(self._node_msg(\n                     'bitcoind exited with status {} during initialization'.format(self.process.returncode)))",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/28253#discussion_r1294678025",
      "id" : 1294678025,
      "in_reply_to_id" : 1294258580,
      "line" : 245,
      "node_id" : "PRRC_kwDOABII585NKzgJ",
      "original_commit_id" : "2f19be69109ddc0baed8c9d2db0c8de791b5f6ad",
      "original_line" : 245,
      "original_position" : 14,
      "original_start_line" : null,
      "path" : "test/functional/test_framework/test_node.py",
      "position" : 14,
      "pull_request_review_id" : 1578689713,
      "pull_request_url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/28253",
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294678025/reactions"
      },
      "side" : "RIGHT",
      "start_line" : null,
      "start_side" : null,
      "subject_type" : "line",
      "updated_at" : "2023-08-15T14:32:47Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294678025",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/5377650?v=4",
         "events_url" : "https://api.github.com/users/furszy/events{/privacy}",
         "followers_url" : "https://api.github.com/users/furszy/followers",
         "following_url" : "https://api.github.com/users/furszy/following{/other_user}",
         "gists_url" : "https://api.github.com/users/furszy/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/furszy",
         "id" : 5377650,
         "login" : "furszy",
         "node_id" : "MDQ6VXNlcjUzNzc2NTA=",
         "organizations_url" : "https://api.github.com/users/furszy/orgs",
         "received_events_url" : "https://api.github.com/users/furszy/received_events",
         "repos_url" : "https://api.github.com/users/furszy/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/furszy/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/furszy/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/furszy"
      }
   },
   {
      "_links" : {
         "html" : {
            "href" : "https://github.com/bitcoin/bitcoin/pull/28253#discussion_r1294687210"
         },
         "pull_request" : {
            "href" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/28253"
         },
         "self" : {
            "href" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294687210"
         }
      },
      "author_association" : "MEMBER",
      "body" : "> In a first glance, that doesn't seems to print the nodes' stderr. That seems to be related to the job stderr (the test run in a subprocess). And those aren't connected.\r\n\r\nCurrently, you are reading the node's stderr and the printing it to stdout, so it *should* appear as `print(BOLD[1] + 'stdout:\\n' + BOLD[0] + stdout + '\\n')`.\r\n\r\n> Ok. The result is pretty much the same. Just the stack trace is a bit longer.\r\n\r\nThe difference should be that the output won't be shown in the CI tail if the test has produced enough output.\r\n\r\n> As far as I can see, we don't support combined output on single test cases. So, that would make us lose the crash cause on individual test runs?\r\n\r\ncombined output is *only* supported for single test files.",
      "commit_id" : "2f19be69109ddc0baed8c9d2db0c8de791b5f6ad",
      "created_at" : "2023-08-15T14:40:36Z",
      "diff_hunk" : "@@ -232,6 +232,15 @@ def wait_for_rpc_connection(self):\n         poll_per_s = 4\n         for _ in range(poll_per_s * self.rpc_timeout):\n             if self.process.poll() is not None:\n+                if self.process.returncode != 0:\n+                    # Print any abrupt shutdown error, so it is visible from the console and the\n+                    # user doesn't have to go node by node checking which one failed.\n+                    with open(self.stderr.name, 'r', encoding='utf-8') as err_file:\n+                        print(\"************************\")\n+                        print(f\"'{self.datadir_path.name}' abruptly aborted with error:\\n\")\n+                        print(''.join(line for line in err_file if line.strip() and line[0] != \"*\"))\n+                        print(\"************************\")\n+\n                 raise FailedToStartError(self._node_msg(\n                     'bitcoind exited with status {} during initialization'.format(self.process.returncode)))",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/28253#discussion_r1294687210",
      "id" : 1294687210,
      "in_reply_to_id" : 1294258580,
      "line" : 245,
      "node_id" : "PRRC_kwDOABII585NK1vq",
      "original_commit_id" : "2f19be69109ddc0baed8c9d2db0c8de791b5f6ad",
      "original_line" : 245,
      "original_position" : 14,
      "original_start_line" : null,
      "path" : "test/functional/test_framework/test_node.py",
      "position" : 14,
      "pull_request_review_id" : 1578704190,
      "pull_request_url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/28253",
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294687210/reactions"
      },
      "side" : "RIGHT",
      "start_line" : null,
      "start_side" : null,
      "subject_type" : "line",
      "updated_at" : "2023-08-15T14:40:36Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/1294687210",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   }
]
