{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "MEMBER",
   "body" : "https://cirrus-ci.com/task/6317902398226432?logs=ci#L3288\r\n```bash\r\n test  2024-03-26T18:25:07.400000Z TestFramework (ERROR): Unexpected exception caught during testing \r\n                                   Traceback (most recent call last):\r\n                                     File \"/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py\", line 132, in main\r\n                                       self.run_test()\r\n                                     File \"/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_coinstatsindex.py\", line 51, in run_test\r\n                                       self._test_coin_stats_index()\r\n                                     File \"/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_coinstatsindex.py\", line 240, in _test_coin_stats_index\r\n                                       self.restart_node(1, extra_args=[\"-coinstatsindex\", \"-reindex-chainstate\"])\r\n                                     File \"/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py\", line 598, in restart_node\r\n                                       self.start_node(i, extra_args)\r\n                                     File \"/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py\", line 550, in start_node\r\n                                       node.wait_for_rpc_connection()\r\n                                     File \"/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_node.py\", line 255, in wait_for_rpc_connection\r\n                                       raise FailedToStartError(self._node_msg(\r\n                                   test_framework.test_node.FailedToStartError: [node 1] bitcoind exited with status 66 during initialization.\r\n test  2024-03-26T18:25:07.402000Z TestFramework (DEBUG): Closing down network thread \r\n```",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 1,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29746/comments",
   "created_at" : "2024-03-27T09:42:04Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29746/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/29746",
   "id" : 2210316103,
   "labels" : [],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29746/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "I_kwDOABII586Dvr9H",
   "number" : 29746,
   "performed_via_github_app" : null,
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29746/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "state_reason" : null,
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29746/timeline",
   "title" : "test: failure in feature_coinstatsindex.py ",
   "updated_at" : "2024-03-27T09:59:51Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29746",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/863730?v=4",
      "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
      "followers_url" : "https://api.github.com/users/fanquake/followers",
      "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
      "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/fanquake",
      "id" : 863730,
      "login" : "fanquake",
      "node_id" : "MDQ6VXNlcjg2MzczMA==",
      "organizations_url" : "https://api.github.com/users/fanquake/orgs",
      "received_events_url" : "https://api.github.com/users/fanquake/received_events",
      "repos_url" : "https://api.github.com/users/fanquake/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/fanquake"
   }
}
