[
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "<!--e57a25ab6845829454e8d69fc972939a-->\n\nThe following sections might be updated with supplementary metadata relevant to reviewers and maintainers.\n\n<!--006a51241073e994b41acfe9ec718e94-->\n### Code Coverage\nFor detailed information about the code coverage, see the [test coverage report](https://corecheck.dev/bitcoin/bitcoin/pulls/29791).\n<!--021abf342d371248e50ceaed478a90ca-->\n### Reviews\nSee [the guideline](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#code-review) for information on the review process.\n| Type | Reviewers |\n| ---- | --------- |\n| ACK | [maflcko](https://github.com/bitcoin/bitcoin/pull/29791#issuecomment-2033837668), [tdb3](https://github.com/bitcoin/bitcoin/pull/29791#issuecomment-2036073972), [BrandonOdiwuor](https://github.com/bitcoin/bitcoin/pull/29791#pullrequestreview-1982820317), [itornaza](https://github.com/bitcoin/bitcoin/pull/29791#issuecomment-2040330763) |\n\nIf your review is incorrectly listed, please react with ð to this comment and the bot will ignore it on the next update.\n",
      "created_at" : "2024-04-02T16:13:08Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29791#issuecomment-2032476789",
      "id" : 2032476789,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29791",
      "node_id" : "IC_kwDOABII5855JSJ1",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2032476789/reactions"
      },
      "updated_at" : "2024-04-05T17:48:55Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2032476789",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/39886733?v=4",
         "events_url" : "https://api.github.com/users/DrahtBot/events{/privacy}",
         "followers_url" : "https://api.github.com/users/DrahtBot/followers",
         "following_url" : "https://api.github.com/users/DrahtBot/following{/other_user}",
         "gists_url" : "https://api.github.com/users/DrahtBot/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/DrahtBot",
         "id" : 39886733,
         "login" : "DrahtBot",
         "node_id" : "MDQ6VXNlcjM5ODg2NzMz",
         "organizations_url" : "https://api.github.com/users/DrahtBot/orgs",
         "received_events_url" : "https://api.github.com/users/DrahtBot/received_events",
         "repos_url" : "https://api.github.com/users/DrahtBot/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/DrahtBot/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/DrahtBot/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/DrahtBot"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Combined logs:\r\n[29791_feature_index_prune_combined_logs.gz](https://github.com/bitcoin/bitcoin/files/14843759/29791_feature_index_prune_combined_logs.gz)\r\n[29791_wallet_importdescriptors_combined_logs.gz](https://github.com/bitcoin/bitcoin/files/14843760/29791_wallet_importdescriptors_combined_logs.gz)\r\n",
      "created_at" : "2024-04-02T20:59:23Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29791#issuecomment-2033089178",
      "id" : 2033089178,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29791",
      "node_id" : "IC_kwDOABII5855Lnqa",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2033089178/reactions"
      },
      "updated_at" : "2024-04-02T20:59:23Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2033089178",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/581308?v=4",
         "events_url" : "https://api.github.com/users/cbergqvist/events{/privacy}",
         "followers_url" : "https://api.github.com/users/cbergqvist/followers",
         "following_url" : "https://api.github.com/users/cbergqvist/following{/other_user}",
         "gists_url" : "https://api.github.com/users/cbergqvist/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/cbergqvist",
         "id" : 581308,
         "login" : "cbergqvist",
         "node_id" : "MDQ6VXNlcjU4MTMwOA==",
         "organizations_url" : "https://api.github.com/users/cbergqvist/orgs",
         "received_events_url" : "https://api.github.com/users/cbergqvist/received_events",
         "repos_url" : "https://api.github.com/users/cbergqvist/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/cbergqvist/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/cbergqvist/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/cbergqvist"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "lgtm ACK 49c0b8b2288e60ae22fcac5d03811cf36ecec058",
      "created_at" : "2024-04-03T08:04:26Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29791#issuecomment-2033837668",
      "id" : 2033837668,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29791",
      "node_id" : "IC_kwDOABII5855OeZk",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 1,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 1,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2033837668/reactions"
      },
      "updated_at" : "2024-04-03T08:04:26Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2033837668",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/maflcko/events{/privacy}",
         "followers_url" : "https://api.github.com/users/maflcko/followers",
         "following_url" : "https://api.github.com/users/maflcko/following{/other_user}",
         "gists_url" : "https://api.github.com/users/maflcko/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/maflcko",
         "id" : 6399679,
         "login" : "maflcko",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/maflcko/orgs",
         "received_events_url" : "https://api.github.com/users/maflcko/received_events",
         "repos_url" : "https://api.github.com/users/maflcko/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/maflcko/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/maflcko/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/maflcko"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Thanks for having a look @tdb3!\r\n\r\nAs mentioned in the summary, running without `--jobs=16` makes the tests succeed. I guess it is not a common parameter (even less common in conjunction with `--extended`).\r\n\r\nYour questions prompted me to perform the tests on older release branches to see if behavior changed recently. (No other tests failed but I didn't let `feature_dbcrash.py` and complete since it takes around 45 minutes (occasionally skipped some other stragglers as well)).\r\n\r\n*27.x* - Only `feature_index_prune.py` failed (4 runs), both failed (2 runs).\r\n\r\n*26.x* - Only `feature_index_prune.py` failed - `wallet_importdescriptors.py --descriptors` succeeded (4 runs)\r\n\r\n*25.x* - Only `feature_index_prune.py` failed - `wallet_importdescriptors.py --descriptors` succeeded (1 runs)\r\n\r\nThe fact that these two tests fail so consistently while no other tests fail helped increase my confidence in this change. The major reason `wallet_importdescriptors.py` is not failing as often probably lies in the difference in how much the timeouts are exceeded.\r\n\r\n> Might be worth running git blame to find the previous PR that is associated with the previous timeouts to see if there is rationale (a stretch, but worth a quick check).\r\n\r\nAgree that it might be fruitful to investigate the history of `wallet_importdescriptors.py` to pinpoint regressions, didn't have time today.",
      "created_at" : "2024-04-03T22:25:07Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29791#issuecomment-2035711744",
      "id" : 2035711744,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29791",
      "node_id" : "IC_kwDOABII5855Vn8A",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2035711744/reactions"
      },
      "updated_at" : "2024-04-03T22:25:07Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2035711744",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/581308?v=4",
         "events_url" : "https://api.github.com/users/cbergqvist/events{/privacy}",
         "followers_url" : "https://api.github.com/users/cbergqvist/followers",
         "following_url" : "https://api.github.com/users/cbergqvist/following{/other_user}",
         "gists_url" : "https://api.github.com/users/cbergqvist/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/cbergqvist",
         "id" : 581308,
         "login" : "cbergqvist",
         "node_id" : "MDQ6VXNlcjU4MTMwOA==",
         "organizations_url" : "https://api.github.com/users/cbergqvist/orgs",
         "received_events_url" : "https://api.github.com/users/cbergqvist/received_events",
         "repos_url" : "https://api.github.com/users/cbergqvist/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/cbergqvist/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/cbergqvist/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/cbergqvist"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "@itornaza subtly prompted me to do some tests to find the sweet spot for the number of jobs on my hardware, which luckily helps motivate why running with 16 jobs is not unreasonable.\r\n\r\nThis is wall time running on a [RAM disk](https://github.com/bitcoin/bitcoin/blob/master/test/README.md#speed-up-test-runs-with-a-ram-disk) **without `--extended`**.\r\n```\r\njobs duration (s) results\r\n4    816          all passed\r\n8    454          all passed\r\n12   342          all passed\r\n16   300          all passed\r\n20   279          all passed\r\n24   264          all passed\r\n26   256          all passed\r\n28   261          all passed\r\n30   260          all passed\r\n```\r\n(These happened to be run on `26.x` branch, running the same on this PR (49c0b8b2288e60ae22fcac5d03811cf36ecec058) with 16 jobs got me 327 seconds, so things haven't moved too much).",
      "created_at" : "2024-04-03T22:28:49Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29791#issuecomment-2035716197",
      "id" : 2035716197,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29791",
      "node_id" : "IC_kwDOABII5855VpBl",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2035716197/reactions"
      },
      "updated_at" : "2024-04-03T22:28:49Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2035716197",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/581308?v=4",
         "events_url" : "https://api.github.com/users/cbergqvist/events{/privacy}",
         "followers_url" : "https://api.github.com/users/cbergqvist/followers",
         "following_url" : "https://api.github.com/users/cbergqvist/following{/other_user}",
         "gists_url" : "https://api.github.com/users/cbergqvist/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/cbergqvist",
         "id" : 581308,
         "login" : "cbergqvist",
         "node_id" : "MDQ6VXNlcjU4MTMwOA==",
         "organizations_url" : "https://api.github.com/users/cbergqvist/orgs",
         "received_events_url" : "https://api.github.com/users/cbergqvist/received_events",
         "repos_url" : "https://api.github.com/users/cbergqvist/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/cbergqvist/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/cbergqvist/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/cbergqvist"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : ">As mentioned in the summary, running without --jobs=16 makes the tests succeed\r\n>\r\nOk, this gives me a bit more confidence that this may just be a simple case of resource contention from high concurrency slowing things down.  Omitting `--jobs` causes the default value of 4 jobs to be used.  In general, IIRC jobs != threads of execution (since some tests run multiple nodes, etc.).  I was also able to reproduce the failure of `feature_index_prune.py` with `--jobs=18` (on master).\r\n\r\n> Your questions prompted me to perform the tests on older release branches to see if behavior changed recently. (No other tests failed but I didn't let `feature_dbcrash.py` and complete since it takes around 45 minutes (occasionally skipped some other stragglers as well)).\r\n> \r\n> _27.x_ - Only `feature_index_prune.py` failed (4 runs), both failed (2 runs).\r\n> \r\n> _26.x_ - Only `feature_index_prune.py` failed - `wallet_importdescriptors.py --descriptors` succeeded (4 runs)\r\n> \r\n> _25.x_ - Only `feature_index_prune.py` failed - `wallet_importdescriptors.py --descriptors` succeeded (1 runs)\r\n> \r\n> The fact that these two tests fail so consistently while no other tests fail helped increase my confidence in this change. \r\n\r\nGood work gathering data.\r\n\r\nSince these tests only seem to be failing with high levels of concurrency, I'm ok with an ACK.  I don't have the time currently to further performance profile this, but maybe someone else does.\r\n\r\nACK for 49c0b8b2288e60ae22fcac5d03811cf36ecec058\r\n",
      "created_at" : "2024-04-04T02:50:53Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29791#issuecomment-2036073972",
      "id" : 2036073972,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29791",
      "node_id" : "IC_kwDOABII5855XAX0",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2036073972/reactions"
      },
      "updated_at" : "2024-04-04T02:50:53Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2036073972",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/106488469?v=4",
         "events_url" : "https://api.github.com/users/tdb3/events{/privacy}",
         "followers_url" : "https://api.github.com/users/tdb3/followers",
         "following_url" : "https://api.github.com/users/tdb3/following{/other_user}",
         "gists_url" : "https://api.github.com/users/tdb3/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/tdb3",
         "id" : 106488469,
         "login" : "tdb3",
         "node_id" : "U_kgDOBljilQ",
         "organizations_url" : "https://api.github.com/users/tdb3/orgs",
         "received_events_url" : "https://api.github.com/users/tdb3/received_events",
         "repos_url" : "https://api.github.com/users/tdb3/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/tdb3/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/tdb3/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/tdb3"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "approach ACK 49c0b8b2288e60ae22fcac5d03811cf36ecec058\r\n\r\nIt is indeed frustrating to watch some functional tests failing by just using 12-16 jobs in parallel. This PR addresses the issue with minimal footprint in the test code. However, the timeout of some tests are even greater on my machine without me understanding the reason yet. Until this issue is resolved, running the extended tests with the default number of jobs seems the best approach to me.\r\n\r\n## On Master branch\r\n\r\nReplicated the errant behavior with the `--extended` flag on the master branch for 12, 13 and 16 jobs with the following functional tests failing:\r\n\r\n```\r\nwallet_importdescriptors.py --descriptors              | â Failed  | 106 s (timeout > 60 s)\r\n```\r\n\r\nand another one not covered in this PR:\r\n\r\n```\r\nwallet_transactiontime_rescan.py --legacy-wallet       | â Failed  | 150 s (not covered by this PR)\r\n```\r\n\r\n## Tests on PR Branch\r\n\r\n- Run all functional tests with `--extended` and the default 4 jobs and all tests pass\r\n- Run all functional tests with `--extended` and `--jobs=13` and all pass except:\r\n\r\n```\r\nwallet_transactiontime_rescan.py --legacy-wallet       | â Failed  | 146 s (not covered by this PR)\r\n```\r\n\r\nwhich is a test not in the scope of this PR anyway.\r\n\r\n- Run all functional tests with `--extended` and `--jobs=16` multiple times and after cleaning the test environment in order to be on the safe side, and all tests pass except:\r\n\r\n```\r\nfeature_index_prune.py                                 | â Failed  | 183 s (timeout > 150 s)\r\nwallet_importdescriptors.py --descriptors              | â Failed  | 122 s (timeout > 10 s)\r\n```\r\n\r\nand again the same test that is not a subject of this PR:\r\n \r\n```\r\nwallet_transactiontime_rescan.py --legacy-wallet       | â Failed  | 159 s (not covered by this PR)\r\n```\r\n\r\nNote: All test run on Apple M2 Max chip and macos 14.4.1 (23E224)\r\n",
      "created_at" : "2024-04-05T17:48:52Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29791#issuecomment-2040330763",
      "id" : 2040330763,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29791",
      "node_id" : "IC_kwDOABII5855nPoL",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2040330763/reactions"
      },
      "updated_at" : "2024-04-05T17:48:52Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2040330763",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/11520757?v=4",
         "events_url" : "https://api.github.com/users/itornaza/events{/privacy}",
         "followers_url" : "https://api.github.com/users/itornaza/followers",
         "following_url" : "https://api.github.com/users/itornaza/following{/other_user}",
         "gists_url" : "https://api.github.com/users/itornaza/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/itornaza",
         "id" : 11520757,
         "login" : "itornaza",
         "node_id" : "MDQ6VXNlcjExNTIwNzU3",
         "organizations_url" : "https://api.github.com/users/itornaza/orgs",
         "received_events_url" : "https://api.github.com/users/itornaza/received_events",
         "repos_url" : "https://api.github.com/users/itornaza/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/itornaza/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/itornaza/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/itornaza"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Thanks for trying it out!\r\n\r\n> and again the same test that is not a subject of this PR:\r\n> \r\n> ```\r\n> wallet_transactiontime_rescan.py --legacy-wallet       | â Failed  | 159 s (not covered by this PR)\r\n> ```\r\n> \r\n> Note: All test run on Apple M2 Max chip and macos 14.4.1 (23E224)\r\n\r\nSearched closed issues and it seems like others running on Mac are also seeing `wallet_transactiontime_rescan.py --legacy-wallet` fail: #28221. Hopefully that specific failure & fix can be addressed in that issue.\r\n\r\n## Edit:\r\n\r\n> ```\r\n> feature_index_prune.py                                 | â Failed  | 183 s (timeout > 150 s)\r\n> wallet_importdescriptors.py --descriptors              | â Failed  | 122 s (timeout > 10 s)\r\n> ```\r\n\r\nWait.. the modified tests still fail with the commit in this PR. Hm.. good find! I could understand maybe bumping the first one from 60 s all the way to 200 s (233% increase). But bumping the second one from 10 s to 150 s is more than 10x. :\\",
      "created_at" : "2024-04-05T20:07:19Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29791#issuecomment-2040552035",
      "id" : 2040552035,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29791",
      "node_id" : "IC_kwDOABII5855oFpj",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2040552035/reactions"
      },
      "updated_at" : "2024-04-05T20:13:44Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2040552035",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/581308?v=4",
         "events_url" : "https://api.github.com/users/cbergqvist/events{/privacy}",
         "followers_url" : "https://api.github.com/users/cbergqvist/followers",
         "following_url" : "https://api.github.com/users/cbergqvist/following{/other_user}",
         "gists_url" : "https://api.github.com/users/cbergqvist/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/cbergqvist",
         "id" : 581308,
         "login" : "cbergqvist",
         "node_id" : "MDQ6VXNlcjU4MTMwOA==",
         "organizations_url" : "https://api.github.com/users/cbergqvist/orgs",
         "received_events_url" : "https://api.github.com/users/cbergqvist/received_events",
         "repos_url" : "https://api.github.com/users/cbergqvist/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/cbergqvist/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/cbergqvist/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/cbergqvist"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "@itornaza if you have the inclination, it might be helpful if you could provide combined logs for the `wallet_importdescriptors.py --descriptors` test when it fails even when using this PR's commit. Then I/we could compare it with the combined logs produced on my machine (uploaded and linked in the first comment) and maybe figure out what lies behind the performance difference.",
      "created_at" : "2024-04-05T20:50:04Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29791#issuecomment-2040608592",
      "id" : 2040608592,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29791",
      "node_id" : "IC_kwDOABII5855oTdQ",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2040608592/reactions"
      },
      "updated_at" : "2024-04-05T20:50:04Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2040608592",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/581308?v=4",
         "events_url" : "https://api.github.com/users/cbergqvist/events{/privacy}",
         "followers_url" : "https://api.github.com/users/cbergqvist/followers",
         "following_url" : "https://api.github.com/users/cbergqvist/following{/other_user}",
         "gists_url" : "https://api.github.com/users/cbergqvist/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/cbergqvist",
         "id" : 581308,
         "login" : "cbergqvist",
         "node_id" : "MDQ6VXNlcjU4MTMwOA==",
         "organizations_url" : "https://api.github.com/users/cbergqvist/orgs",
         "received_events_url" : "https://api.github.com/users/cbergqvist/received_events",
         "repos_url" : "https://api.github.com/users/cbergqvist/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/cbergqvist/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/cbergqvist/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/cbergqvist"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "@cbergqvist  I re-run today the `test/functional/test_runner.py --jobs=16 --extended` two times on the **PR branch** after cleaning up everything and building the branch again. I include the log files for each of the errors. I will happily assist you since my current goal is to build up confidence in running the test harness! \r\n\r\n## First run\r\n\r\n```\r\nwallet_importdescriptors.py --descriptors              | â Failed  | 139 s \r\nwallet_transactiontime_rescan.py --legacy-wallet       | â Failed  | 161 s\r\n```\r\n\r\n<details>\r\n\r\n<summary>wallet_importdescriptors log</summary>\r\n\r\n```\r\n2024-04-06T10:09:11.791000Z TestFramework (INFO): PRNG seed is: 311790312446680818\r\n2024-04-06T10:09:11.802000Z TestFramework (DEBUG): Setting up network thread\r\n2024-04-06T10:09:11.806000Z TestFramework (INFO): Initializing test directory /var/folders/qy/mc4396sn0ql8dpl5q852sng40000gn/T/test_runner_â¿_ð_20240406_130246/wallet_importdescriptors_98\r\n2024-04-06T10:09:11.897000Z TestFramework.node0 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-06T10:09:11.911000Z TestFramework.node1 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-06T10:09:12.981000Z TestFramework.node0 (DEBUG): RPC successfully started\r\n2024-04-06T10:09:13.007000Z TestFramework.node1 (DEBUG): RPC successfully started\r\n2024-04-06T10:09:13.244000Z TestFramework (INFO): Setting up wallets\r\n2024-04-06T10:09:14.489000Z TestFramework (INFO): Mining coins\r\n2024-04-06T10:09:24.007000Z TestFramework (INFO): Import should fail if a descriptor is not provided\r\n2024-04-06T10:09:24.029000Z TestFramework (INFO): Should import a p2pkh descriptor\r\n2024-04-06T10:09:24.158000Z TestFramework (INFO): Test can import same descriptor with public key twice\r\n2024-04-06T10:09:24.250000Z TestFramework (INFO): Test can update descriptor label\r\n2024-04-06T10:09:24.326000Z TestFramework (INFO): Internal addresses cannot have labels\r\n2024-04-06T10:09:24.346000Z TestFramework (INFO): Internal addresses should be detected as such\r\n2024-04-06T10:09:24.423000Z TestFramework (INFO): Should not import a p2sh-p2wpkh descriptor without checksum\r\n2024-04-06T10:09:24.439000Z TestFramework (INFO): Should not import a p2sh-p2wpkh descriptor that has range specified\r\n2024-04-06T10:09:24.463000Z TestFramework (INFO): Should not import a p2sh-p2wpkh descriptor and have it set to active\r\n2024-04-06T10:09:24.487000Z TestFramework (INFO): Should import a (non-active) p2sh-p2wpkh descriptor\r\n2024-04-06T10:09:24.957000Z TestFramework (INFO): Should import a 1-of-2 bare multisig from descriptor\r\n2024-04-06T10:09:25.024000Z TestFramework (INFO): Should not treat individual keys from the imported bare multisig as watchonly\r\n2024-04-06T10:09:25.050000Z TestFramework (INFO): Ranged descriptors cannot have labels\r\n2024-04-06T10:09:25.067000Z TestFramework (INFO): Private keys required for private keys enabled wallet\r\n2024-04-06T10:09:25.078000Z TestFramework (INFO): Ranged descriptor import should warn without a specified range\r\n2024-04-06T10:09:25.115000Z TestFramework (INFO): Should not import a ranged descriptor that includes xpriv into a watch-only wallet\r\n2024-04-06T10:09:25.124000Z TestFramework (INFO): Should not import a descriptor with hardened derivations when private keys are disabled\r\n2024-04-06T10:09:25.197000Z TestFramework (INFO): Verify we can only extend descriptor's range\r\n2024-04-06T10:09:25.619000Z TestFramework (INFO): Check we can change descriptor internal flag\r\n2024-04-06T10:09:25.846000Z TestFramework (INFO): Key ranges should be imported in order\r\n2024-04-06T10:09:26.635000Z TestFramework (INFO): Check we can change next_index\r\n2024-04-06T10:09:27.244000Z TestFramework (INFO): Check imported descriptors are not active by default\r\n2024-04-06T10:09:27.334000Z TestFramework (INFO): Check can activate inactive descriptor\r\n2024-04-06T10:09:27.435000Z TestFramework (INFO): Check can deactivate active descriptor\r\n2024-04-06T10:09:27.568000Z TestFramework (INFO): Verify activation state is persistent\r\n2024-04-06T10:09:27.980000Z TestFramework (INFO): Should import a descriptor with a WIF private key as spendable\r\n2024-04-06T10:09:28.053000Z TestFramework (INFO): Test can import same descriptor with private key twice\r\n2024-04-06T10:09:28.935000Z TestFramework (INFO): Test that multisigs can be imported, signed for, and getnewaddress'd\r\n2024-04-06T10:09:29.665000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-06T10:09:32.954000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-06T10:09:34.163000Z TestFramework (INFO): Multisig with distributed keys\r\n2024-04-06T10:09:34.612000Z TestFramework (INFO): We can create and use a huge multisig under P2WSH\r\n2024-04-06T10:09:35.489000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-06T10:09:35.501000Z TestFramework (INFO): Under P2SH, multisig are standard with up to 15 compressed keys\r\n2024-04-06T10:09:36.347000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-06T10:09:37.714000Z TestFramework (INFO): Amending multisig with new private keys\r\n2024-04-06T10:09:38.065000Z TestFramework (INFO): Combo descriptors cannot be active\r\n2024-04-06T10:09:38.065000Z TestFramework (INFO): Descriptors with no type cannot be active\r\n2024-04-06T10:09:38.079000Z TestFramework (INFO): Test importing a descriptor to an encrypted wallet\r\n2024-04-06T10:10:30.316000Z TestFramework (ERROR): Assertion failed\r\nTraceback (most recent call last):\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/test_framework.py\", line 132, in main\r\n    self.run_test()\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/wallet_importdescriptors.py\", line 692, in run_test\r\n    importing = thread.submit(encrypted_wallet.importdescriptors, requests=[descriptor])\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py\", line 124, in __exit__\r\n    next(self.gen)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/test_node.py\", line 490, in assert_debug_log\r\n    self._raise_assertion_error('Expected messages \"{}\" does not partially match log:\\n\\n{}\\n\\n'.format(str(expected_msgs), print_log))\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/test_node.py\", line 188, in _raise_assertion_error\r\n    raise AssertionError(self._node_msg(msg))\r\nAssertionError: [node 0] Expected messages \"['Rescan started from block 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206... (slow variant inspecting all blocks)']\" does not partially match log:\r\n\r\n - 2024-04-06T10:10:00.315333Z [http] [httpserver.cpp:306] [http_request_cb] [http] Received a POST request for /wallet/encrypted_wallet from 127.0.0.1:63874\r\n - 2024-04-06T10:10:00.320140Z [httpworker.0] [rpc/request.cpp:187] [parse] [rpc] ThreadRPCServer method=importdescriptors user=__cookie__\r\n \r\n ...\r\n \r\n - 2024-04-06T10:10:10.303007Z [httpworker.0] [wallet/sqlite.cpp:57] [TraceSqlCallback] [/var/folders/qy/mc4396sn0ql8dpl5q852sng40000gn/T/test_runner_â¿_ð_20240406_130246/wallet_importdescriptors_98/node0/regtest/wallets/encrypted_wallet/wallet.dat] SQLite Statement: INSERT or REPLACE into main values(?, ?)\r\n - 2024-04-06T10:10:10.306904Z [httpworker.0] [wallet/sqlite.cpp:57] [TraceSqlCallback] [/var/folders/qy/mc4396sn0ql8dpl5q852sng40000gn/T/test_runner_â¿_ð_20240406_130246/wallet_importdescriptors_98/node0/regtest/wallets/encrypted_wallet/wallet.dat] SQLite Statement: INSERT or REPLACE into main values(?, ?)\r\n\r\n\r\n2024-04-06T10:10:30.324000Z TestFramework (DEBUG): Closing down network thread\r\n2024-04-06T10:10:30.380000Z TestFramework (INFO): Stopping nodes\r\n2024-04-06T10:10:30.389000Z TestFramework.node0 (DEBUG): Stopping node\r\n2024-04-06T10:10:30.390000Z TestFramework.node0 (ERROR): Unable to stop node.\r\nTraceback (most recent call last):\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/test_node.py\", line 375, in stop_node\r\n    self.stop(wait=wait)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/coverage.py\", line 50, in __call__\r\n    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 127, in __call__\r\n    response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 105, in _request\r\n    self.__conn.request(method, path, postdata, headers)\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 1257, in request\r\n    self._send_request(method, url, body, headers, encode_chunked)\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 1268, in _send_request\r\n    self.putrequest(method, url, **skips)\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 1094, in putrequest\r\n    raise CannotSendRequest(self.__state)\r\nhttp.client.CannotSendRequest: Request-sent\r\n2024-04-06T10:10:30.395000Z TestFramework.node1 (DEBUG): Stopping node\r\n2024-04-06T10:11:30.443000Z TestFramework.utils (ERROR): wait_until() failed. Predicate: ''''\r\n        self.wait_until(lambda: self.is_node_stopped(expected_ret_code=expected_ret_code, **kwargs), timeout=timeout)\r\n'''\r\n\r\n```\r\n\r\n</details>\r\n\r\n\r\n<details>\r\n\r\n<summary>wallet_transactiontime_rescan log</summary>\r\n\r\n```\r\n2024-04-06T10:07:52.362000Z TestFramework (INFO): PRNG seed is: 5681009932255616667\r\n2024-04-06T10:07:52.367000Z TestFramework (DEBUG): Setting up network thread\r\n2024-04-06T10:07:52.367000Z TestFramework (INFO): Initializing test directory /var/folders/qy/mc4396sn0ql8dpl5q852sng40000gn/T/test_runner_â¿_ð_20240406_130246/wallet_transactiontime_rescan_173\r\n2024-04-06T10:07:52.368000Z TestFramework (DEBUG): Copy cache directory /Users/ioannis/Documents/projects/bitcoin/bitcoin/test/cache/node0 to node 0\r\n2024-04-06T10:07:52.427000Z TestFramework (DEBUG): Copy cache directory /Users/ioannis/Documents/projects/bitcoin/bitcoin/test/cache/node0 to node 1\r\n2024-04-06T10:07:52.511000Z TestFramework (DEBUG): Copy cache directory /Users/ioannis/Documents/projects/bitcoin/bitcoin/test/cache/node0 to node 2\r\n2024-04-06T10:07:52.760000Z TestFramework.node0 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-06T10:07:52.774000Z TestFramework.node1 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-06T10:07:52.783000Z TestFramework.node2 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-06T10:07:53.599000Z TestFramework.node0 (DEBUG): RPC successfully started\r\n2024-04-06T10:07:53.629000Z TestFramework.node1 (DEBUG): RPC successfully started\r\n2024-04-06T10:07:53.662000Z TestFramework.node2 (DEBUG): RPC successfully started\r\n2024-04-06T10:07:56.822000Z TestFramework (DEBUG): Generate a block with current time\r\n2024-04-06T10:07:56.826000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-06T10:07:57.259000Z TestFramework (INFO): Prepare nodes and wallet\r\n2024-04-06T10:07:59.483000Z TestFramework (INFO): Start transactions\r\n2024-04-06T10:08:03.676000Z TestFramework (INFO): Send 10 btc to user\r\n2024-04-06T10:08:05.553000Z TestFramework (INFO): Send 5 btc to user\r\n2024-04-06T10:08:07.670000Z TestFramework (INFO): Send 1 btc to user\r\n2024-04-06T10:08:11.447000Z TestFramework (INFO): Check user's final balance and transaction count\r\n2024-04-06T10:08:11.457000Z TestFramework (INFO): Check transaction times\r\n2024-04-06T10:08:11.475000Z TestFramework (INFO): Restore user wallet on another node without rescan\r\n2024-04-06T10:08:11.947000Z TestFramework (INFO): Rescan last history part\r\n2024-04-06T10:08:12.007000Z TestFramework (INFO): Rescan all history\r\n2024-04-06T10:08:12.083000Z TestFramework (INFO): Check user's final balance and transaction count after restoration\r\n2024-04-06T10:08:12.097000Z TestFramework (INFO): Check transaction times after restoration\r\n2024-04-06T10:08:12.124000Z TestFramework (INFO): Test handling of invalid parameters for rescanblockchain\r\n2024-04-06T10:08:12.128000Z TestFramework (INFO): Test `rescanblockchain` fails when wallet is encrypted and locked\r\n2024-04-06T10:08:13.302000Z TestFramework (INFO): Test rescanning an encrypted wallet\r\n2024-04-06T10:08:47.620000Z TestFramework.bitcoincli (DEBUG): Running bitcoin-cli ['-rpcwallet=encrypted_wallet', 'walletpassphrase', 'passphrase', '1']\r\n2024-04-06T10:09:33.005000Z TestFramework.bitcoincli (DEBUG): Running bitcoin-cli ['-rpcwallet=encrypted_wallet', 'walletlock']\r\n2024-04-06T10:09:33.010000Z TestFramework.bitcoincli (DEBUG): Running bitcoin-cli ['-rpcwallet=encrypted_wallet', 'walletpassphrasechange', 'passphrase', 'newpassphrase']\r\n2024-04-06T10:09:33.021000Z TestFramework (ERROR): JSONRPC error\r\nTraceback (most recent call last):\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 151, in _get_response\r\n    http_response = self.__conn.getresponse()\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 1349, in getresponse\r\n    response.begin()\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 316, in begin\r\n    version, status, reason = self._read_status()\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 277, in _read_status\r\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py\", line 704, in readinto\r\n    return self._sock.recv_into(b)\r\nsocket.timeout: timed out\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/test_framework.py\", line 132, in main\r\n    self.run_test()\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/wallet_transactiontime_rescan.py\", line 221, in run_test\r\n    assert_equal(rescanning.result(), {\"start_height\": 0, \"stop_height\": 803})\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py\", line 438, in result\r\n    return self.__get_result()\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py\", line 390, in __get_result\r\n    raise self._exception\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py\", line 52, in run\r\n    result = self.fn(*self.args, **self.kwargs)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/coverage.py\", line 50, in __call__\r\n    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 127, in __call__\r\n    response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 106, in _request\r\n    return self._get_response()\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 153, in _get_response\r\n    raise JSONRPCException({\r\ntest_framework.authproxy.JSONRPCException: 'rescanblockchain' RPC took longer than 30.000000 seconds. Consider using larger timeout for calls that take longer to return. (-344)\r\n2024-04-06T10:09:33.029000Z TestFramework (DEBUG): Closing down network thread\r\n2024-04-06T10:09:33.083000Z TestFramework (INFO): Stopping nodes\r\n2024-04-06T10:09:33.084000Z TestFramework.node0 (DEBUG): Stopping node\r\n2024-04-06T10:09:33.084000Z TestFramework.node0 (ERROR): Unable to stop node.\r\nTraceback (most recent call last):\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/test_node.py\", line 375, in stop_node\r\n    self.stop(wait=wait)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/coverage.py\", line 50, in __call__\r\n    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 127, in __call__\r\n    response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 105, in _request\r\n    self.__conn.request(method, path, postdata, headers)\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 1257, in request\r\n    self._send_request(method, url, body, headers, encode_chunked)\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 1268, in _send_request\r\n    self.putrequest(method, url, **skips)\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 1094, in putrequest\r\n    raise CannotSendRequest(self.__state)\r\nhttp.client.CannotSendRequest: Request-sent\r\n2024-04-06T10:09:33.087000Z TestFramework.node1 (DEBUG): Stopping node\r\n2024-04-06T10:09:33.088000Z TestFramework.node2 (DEBUG): Stopping node\r\n2024-04-06T10:10:33.103000Z TestFramework.utils (ERROR): wait_until() failed. Predicate: ''''\r\n        self.wait_until(lambda: self.is_node_stopped(expected_ret_code=expected_ret_code, **kwargs), timeout=timeout)\r\n'''\r\n\r\n```\r\n\r\n</details>\r\n\r\n## Second run\r\n\r\n```\r\nwallet_importdescriptors.py --descriptors              | â Failed  | 138 s\r\nwallet_transactiontime_rescan.py --legacy-wallet       | â Failed  | 159 s\r\n```\r\n\r\n\r\n<details>\r\n\r\n<summary>wallet_importdescriptors log</summary>\r\n\r\n```\r\n2024-04-06T12:24:20.204000Z TestFramework (INFO): PRNG seed is: 2127799964856154174\r\n2024-04-06T12:24:20.208000Z TestFramework (DEBUG): Setting up network thread\r\n2024-04-06T12:24:20.213000Z TestFramework (INFO): Initializing test directory /var/folders/qy/mc4396sn0ql8dpl5q852sng40000gn/T/test_runner_â¿_ð_20240406_151754/wallet_importdescriptors_98\r\n2024-04-06T12:24:20.304000Z TestFramework.node0 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-06T12:24:20.315000Z TestFramework.node1 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-06T12:24:21.366000Z TestFramework.node0 (DEBUG): RPC successfully started\r\n2024-04-06T12:24:21.385000Z TestFramework.node1 (DEBUG): RPC successfully started\r\n2024-04-06T12:24:21.610000Z TestFramework (INFO): Setting up wallets\r\n2024-04-06T12:24:22.615000Z TestFramework (INFO): Mining coins\r\n2024-04-06T12:24:29.829000Z TestFramework (INFO): Import should fail if a descriptor is not provided\r\n2024-04-06T12:24:29.856000Z TestFramework (INFO): Should import a p2pkh descriptor\r\n2024-04-06T12:24:29.950000Z TestFramework (INFO): Test can import same descriptor with public key twice\r\n2024-04-06T12:24:30.021000Z TestFramework (INFO): Test can update descriptor label\r\n2024-04-06T12:24:30.107000Z TestFramework (INFO): Internal addresses cannot have labels\r\n2024-04-06T12:24:30.142000Z TestFramework (INFO): Internal addresses should be detected as such\r\n2024-04-06T12:24:30.228000Z TestFramework (INFO): Should not import a p2sh-p2wpkh descriptor without checksum\r\n2024-04-06T12:24:30.252000Z TestFramework (INFO): Should not import a p2sh-p2wpkh descriptor that has range specified\r\n2024-04-06T12:24:30.272000Z TestFramework (INFO): Should not import a p2sh-p2wpkh descriptor and have it set to active\r\n2024-04-06T12:24:30.292000Z TestFramework (INFO): Should import a (non-active) p2sh-p2wpkh descriptor\r\n2024-04-06T12:24:30.669000Z TestFramework (INFO): Should import a 1-of-2 bare multisig from descriptor\r\n2024-04-06T12:24:30.701000Z TestFramework (INFO): Should not treat individual keys from the imported bare multisig as watchonly\r\n2024-04-06T12:24:30.714000Z TestFramework (INFO): Ranged descriptors cannot have labels\r\n2024-04-06T12:24:30.724000Z TestFramework (INFO): Private keys required for private keys enabled wallet\r\n2024-04-06T12:24:30.741000Z TestFramework (INFO): Ranged descriptor import should warn without a specified range\r\n2024-04-06T12:24:30.775000Z TestFramework (INFO): Should not import a ranged descriptor that includes xpriv into a watch-only wallet\r\n2024-04-06T12:24:30.795000Z TestFramework (INFO): Should not import a descriptor with hardened derivations when private keys are disabled\r\n2024-04-06T12:24:30.882000Z TestFramework (INFO): Verify we can only extend descriptor's range\r\n2024-04-06T12:24:31.144000Z TestFramework (INFO): Check we can change descriptor internal flag\r\n2024-04-06T12:24:31.372000Z TestFramework (INFO): Key ranges should be imported in order\r\n2024-04-06T12:24:32.255000Z TestFramework (INFO): Check we can change next_index\r\n2024-04-06T12:24:32.634000Z TestFramework (INFO): Check imported descriptors are not active by default\r\n2024-04-06T12:24:32.707000Z TestFramework (INFO): Check can activate inactive descriptor\r\n2024-04-06T12:24:32.804000Z TestFramework (INFO): Check can deactivate active descriptor\r\n2024-04-06T12:24:32.902000Z TestFramework (INFO): Verify activation state is persistent\r\n2024-04-06T12:24:33.479000Z TestFramework (INFO): Should import a descriptor with a WIF private key as spendable\r\n2024-04-06T12:24:33.613000Z TestFramework (INFO): Test can import same descriptor with private key twice\r\n2024-04-06T12:24:34.876000Z TestFramework (INFO): Test that multisigs can be imported, signed for, and getnewaddress'd\r\n2024-04-06T12:24:35.465000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-06T12:24:38.152000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-06T12:24:39.820000Z TestFramework (INFO): Multisig with distributed keys\r\n2024-04-06T12:24:40.664000Z TestFramework (INFO): We can create and use a huge multisig under P2WSH\r\n2024-04-06T12:24:41.778000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-06T12:24:41.895000Z TestFramework (INFO): Under P2SH, multisig are standard with up to 15 compressed keys\r\n2024-04-06T12:24:42.673000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-06T12:24:44.195000Z TestFramework (INFO): Amending multisig with new private keys\r\n2024-04-06T12:24:44.673000Z TestFramework (INFO): Combo descriptors cannot be active\r\n2024-04-06T12:24:44.689000Z TestFramework (INFO): Descriptors with no type cannot be active\r\n2024-04-06T12:24:44.716000Z TestFramework (INFO): Test importing a descriptor to an encrypted wallet\r\n2024-04-06T12:25:38.048000Z TestFramework (ERROR): Assertion failed\r\nTraceback (most recent call last):\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/test_framework.py\", line 132, in main\r\n    self.run_test()\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/wallet_importdescriptors.py\", line 692, in run_test\r\n    importing = thread.submit(encrypted_wallet.importdescriptors, requests=[descriptor])\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py\", line 124, in __exit__\r\n    next(self.gen)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/test_node.py\", line 490, in assert_debug_log\r\n    self._raise_assertion_error('Expected messages \"{}\" does not partially match log:\\n\\n{}\\n\\n'.format(str(expected_msgs), print_log))\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/test_node.py\", line 188, in _raise_assertion_error\r\n    raise AssertionError(self._node_msg(msg))\r\nAssertionError: [node 0] Expected messages \"['Rescan started from block 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206... (slow variant inspecting all blocks)']\" does not partially match log:\r\n\r\n - 2024-04-06T12:25:08.046740Z [http] [httpserver.cpp:306] [http_request_cb] [http] Received a POST request for /wallet/encrypted_wallet from 127.0.0.1:52070\r\n - 2024-04-06T12:25:08.061430Z [httpworker.2] [rpc/request.cpp:187] [parse] [rpc] ThreadRPCServer method=importdescriptors user=__cookie__\r\n \r\n ...\r\n\r\n - 2024-04-06T12:25:18.066846Z [httpworker.2] [wallet/sqlite.cpp:57] [TraceSqlCallback] [/var/folders/qy/mc4396sn0ql8dpl5q852sng40000gn/T/test_runner_â¿_ð_20240406_151754/wallet_importdescriptors_98/node0/regtest/wallets/encrypted_wallet/wallet.dat] SQLite Statement: INSERT or REPLACE into main values(?, ?)\r\n - 2024-04-06T12:25:18.072715Z [httpworker.2] [wallet/sqlite.cpp:57] [TraceSqlCallback] [/var/folders/qy/mc4396sn0ql8dpl5q852sng40000gn/T/test_runner_â¿_ð_20240406_151754/wallet_importdescriptors_98/node0/regtest/wallets/encrypted_wallet/wallet.dat] SQLite Statement: INSERT or REPLACE into main values(?, ?)\r\n\r\n\r\n2024-04-06T12:25:38.060000Z TestFramework (DEBUG): Closing down network thread\r\n2024-04-06T12:25:38.118000Z TestFramework (INFO): Stopping nodes\r\n2024-04-06T12:25:38.127000Z TestFramework.node0 (DEBUG): Stopping node\r\n2024-04-06T12:25:38.132000Z TestFramework.node0 (ERROR): Unable to stop node.\r\nTraceback (most recent call last):\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/test_node.py\", line 375, in stop_node\r\n    self.stop(wait=wait)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/coverage.py\", line 50, in __call__\r\n    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 127, in __call__\r\n    response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 105, in _request\r\n    self.__conn.request(method, path, postdata, headers)\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 1257, in request\r\n    self._send_request(method, url, body, headers, encode_chunked)\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 1268, in _send_request\r\n    self.putrequest(method, url, **skips)\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 1094, in putrequest\r\n    raise CannotSendRequest(self.__state)\r\nhttp.client.CannotSendRequest: Request-sent\r\n2024-04-06T12:25:38.146000Z TestFramework.node1 (DEBUG): Stopping node\r\n2024-04-06T12:26:38.208000Z TestFramework.utils (ERROR): wait_until() failed. Predicate: ''''\r\n        self.wait_until(lambda: self.is_node_stopped(expected_ret_code=expected_ret_code, **kwargs), timeout=timeout)\r\n'''\r\n\r\n```\r\n\r\n</details>\r\n\r\n\r\n<details>\r\n\r\n<summary>wallet_transactiontime_rescan log</summary>\r\n\r\n```\r\n2024-04-06T12:23:06.242000Z TestFramework (INFO): PRNG seed is: 2374416369969835520\r\n2024-04-06T12:23:06.245000Z TestFramework (DEBUG): Setting up network thread\r\n2024-04-06T12:23:06.246000Z TestFramework (INFO): Initializing test directory /var/folders/qy/mc4396sn0ql8dpl5q852sng40000gn/T/test_runner_â¿_ð_20240406_151754/wallet_transactiontime_rescan_173\r\n2024-04-06T12:23:06.251000Z TestFramework (DEBUG): Copy cache directory /Users/ioannis/Documents/projects/bitcoin/bitcoin/test/cache/node0 to node 0\r\n2024-04-06T12:23:06.308000Z TestFramework (DEBUG): Copy cache directory /Users/ioannis/Documents/projects/bitcoin/bitcoin/test/cache/node0 to node 1\r\n2024-04-06T12:23:06.345000Z TestFramework (DEBUG): Copy cache directory /Users/ioannis/Documents/projects/bitcoin/bitcoin/test/cache/node0 to node 2\r\n2024-04-06T12:23:06.354000Z TestFramework.node0 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-06T12:23:06.356000Z TestFramework.node1 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-06T12:23:06.360000Z TestFramework.node2 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-06T12:23:06.894000Z TestFramework.node0 (DEBUG): RPC successfully started\r\n2024-04-06T12:23:06.913000Z TestFramework.node1 (DEBUG): RPC successfully started\r\n2024-04-06T12:23:06.925000Z TestFramework.node2 (DEBUG): RPC successfully started\r\n2024-04-06T12:23:10.098000Z TestFramework (DEBUG): Generate a block with current time\r\n2024-04-06T12:23:10.104000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-06T12:23:10.634000Z TestFramework (INFO): Prepare nodes and wallet\r\n2024-04-06T12:23:12.499000Z TestFramework (INFO): Start transactions\r\n2024-04-06T12:23:17.588000Z TestFramework (INFO): Send 10 btc to user\r\n2024-04-06T12:23:20.995000Z TestFramework (INFO): Send 5 btc to user\r\n2024-04-06T12:23:25.219000Z TestFramework (INFO): Send 1 btc to user\r\n2024-04-06T12:23:28.556000Z TestFramework (INFO): Check user's final balance and transaction count\r\n2024-04-06T12:23:28.557000Z TestFramework (INFO): Check transaction times\r\n2024-04-06T12:23:28.561000Z TestFramework (INFO): Restore user wallet on another node without rescan\r\n2024-04-06T12:23:28.989000Z TestFramework (INFO): Rescan last history part\r\n2024-04-06T12:23:29.008000Z TestFramework (INFO): Rescan all history\r\n2024-04-06T12:23:29.038000Z TestFramework (INFO): Check user's final balance and transaction count after restoration\r\n2024-04-06T12:23:29.066000Z TestFramework (INFO): Check transaction times after restoration\r\n2024-04-06T12:23:29.086000Z TestFramework (INFO): Test handling of invalid parameters for rescanblockchain\r\n2024-04-06T12:23:29.113000Z TestFramework (INFO): Test `rescanblockchain` fails when wallet is encrypted and locked\r\n2024-04-06T12:23:30.408000Z TestFramework (INFO): Test rescanning an encrypted wallet\r\n2024-04-06T12:24:02.955000Z TestFramework.bitcoincli (DEBUG): Running bitcoin-cli ['-rpcwallet=encrypted_wallet', 'walletpassphrase', 'passphrase', '1']\r\n2024-04-06T12:24:45.454000Z TestFramework.bitcoincli (DEBUG): Running bitcoin-cli ['-rpcwallet=encrypted_wallet', 'walletlock']\r\n2024-04-06T12:24:45.461000Z TestFramework.bitcoincli (DEBUG): Running bitcoin-cli ['-rpcwallet=encrypted_wallet', 'walletpassphrasechange', 'passphrase', 'newpassphrase']\r\n2024-04-06T12:24:45.470000Z TestFramework (ERROR): JSONRPC error\r\nTraceback (most recent call last):\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 151, in _get_response\r\n    http_response = self.__conn.getresponse()\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 1349, in getresponse\r\n    response.begin()\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 316, in begin\r\n    version, status, reason = self._read_status()\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 277, in _read_status\r\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py\", line 704, in readinto\r\n    return self._sock.recv_into(b)\r\nsocket.timeout: timed out\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/test_framework.py\", line 132, in main\r\n    self.run_test()\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/wallet_transactiontime_rescan.py\", line 221, in run_test\r\n    assert_equal(rescanning.result(), {\"start_height\": 0, \"stop_height\": 803})\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py\", line 438, in result\r\n    return self.__get_result()\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py\", line 390, in __get_result\r\n    raise self._exception\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py\", line 52, in run\r\n    result = self.fn(*self.args, **self.kwargs)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/coverage.py\", line 50, in __call__\r\n    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 127, in __call__\r\n    response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 106, in _request\r\n    return self._get_response()\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 153, in _get_response\r\n    raise JSONRPCException({\r\ntest_framework.authproxy.JSONRPCException: 'rescanblockchain' RPC took longer than 30.000000 seconds. Consider using larger timeout for calls that take longer to return. (-344)\r\n2024-04-06T12:24:45.477000Z TestFramework (DEBUG): Closing down network thread\r\n2024-04-06T12:24:45.532000Z TestFramework (INFO): Stopping nodes\r\n2024-04-06T12:24:45.533000Z TestFramework.node0 (DEBUG): Stopping node\r\n2024-04-06T12:24:45.539000Z TestFramework.node0 (ERROR): Unable to stop node.\r\nTraceback (most recent call last):\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/test_node.py\", line 375, in stop_node\r\n    self.stop(wait=wait)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/coverage.py\", line 50, in __call__\r\n    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 127, in __call__\r\n    response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 105, in _request\r\n    self.__conn.request(method, path, postdata, headers)\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 1257, in request\r\n    self._send_request(method, url, body, headers, encode_chunked)\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 1268, in _send_request\r\n    self.putrequest(method, url, **skips)\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 1094, in putrequest\r\n    raise CannotSendRequest(self.__state)\r\nhttp.client.CannotSendRequest: Request-sent\r\n2024-04-06T12:24:45.544000Z TestFramework.node1 (DEBUG): Stopping node\r\n2024-04-06T12:24:45.545000Z TestFramework.node2 (DEBUG): Stopping node\r\n2024-04-06T12:25:45.577000Z TestFramework.utils (ERROR): wait_until() failed. Predicate: ''''\r\n        self.wait_until(lambda: self.is_node_stopped(expected_ret_code=expected_ret_code, **kwargs), timeout=timeout)\r\n'''\r\n\r\n```\r\n\r\n</details>\r\n\r\n## feature_index_prune\r\n\r\nThis test passed today on both runs on the PR branch, so I only include the log file from the failure I encountered in yesterday's tests (again on the PR branch).\r\n\r\n```\r\nfeature_index_prune.py                                 | â Failed  | 183 s \r\n```\r\n\r\n<details>\r\n\r\n<summary>feature_index_prune log file</summary>\r\n\r\n```\r\n2024-04-05T17:00:49.259000Z TestFramework (INFO): PRNG seed is: 4962004092256186875\r\n2024-04-05T17:00:49.259000Z TestFramework (DEBUG): Setting up network thread\r\n2024-04-05T17:00:49.260000Z TestFramework (INFO): Initializing test directory /var/folders/qy/mc4396sn0ql8dpl5q852sng40000gn/T/test_runner_â¿_ð_20240405_200041/feature_index_prune_302\r\n2024-04-05T17:00:49.261000Z TestFramework (DEBUG): Copy cache directory /Users/ioannis/Documents/projects/bitcoin/bitcoin/test/cache/node0 to node 0\r\n2024-04-05T17:00:49.273000Z TestFramework (DEBUG): Copy cache directory /Users/ioannis/Documents/projects/bitcoin/bitcoin/test/cache/node0 to node 1\r\n2024-04-05T17:00:49.285000Z TestFramework (DEBUG): Copy cache directory /Users/ioannis/Documents/projects/bitcoin/bitcoin/test/cache/node0 to node 2\r\n2024-04-05T17:00:49.407000Z TestFramework (DEBUG): Copy cache directory /Users/ioannis/Documents/projects/bitcoin/bitcoin/test/cache/node0 to node 3\r\n2024-04-05T17:00:49.914000Z TestFramework.node0 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-05T17:00:49.938000Z TestFramework.node1 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-05T17:00:49.962000Z TestFramework.node2 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-05T17:00:50.006000Z TestFramework.node3 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-05T17:00:51.965000Z TestFramework.node0 (DEBUG): RPC successfully started\r\n2024-04-05T17:00:51.983000Z TestFramework.node1 (DEBUG): RPC successfully started\r\n2024-04-05T17:00:52.007000Z TestFramework.node2 (DEBUG): RPC successfully started\r\n2024-04-05T17:00:52.035000Z TestFramework.node3 (DEBUG): RPC successfully started\r\n2024-04-05T17:00:52.080000Z TestFramework (DEBUG): Generate a block with current time\r\n2024-04-05T17:00:52.086000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-05T17:00:52.957000Z TestFramework (INFO): check if we can access blockfilters and coinstats when pruning is enabled but no blocks are actually pruned\r\n2024-04-05T17:00:53.259000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-05T17:00:55.968000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-05T17:01:00.604000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-05T17:01:00.646000Z TestFramework (INFO): prune some blocks\r\n2024-04-05T17:01:00.702000Z TestFramework (INFO): check if we can access the tips blockfilter and coinstats when we have pruned some blocks\r\n2024-04-05T17:01:00.767000Z TestFramework (INFO): check if we can access the blockfilter and coinstats of a pruned block\r\n2024-04-05T17:01:00.818000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-05T17:01:02.172000Z TestFramework.node0 (DEBUG): Stopping node\r\n2024-04-05T17:01:02.390000Z TestFramework.node0 (DEBUG): Node stopped\r\n2024-04-05T17:01:02.393000Z TestFramework.node0 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-05T17:01:02.918000Z TestFramework.node0 (DEBUG): RPC successfully started\r\n2024-04-05T17:01:02.918000Z TestFramework.node1 (DEBUG): Stopping node\r\n2024-04-05T17:01:03.084000Z TestFramework.node1 (DEBUG): Node stopped\r\n2024-04-05T17:01:03.090000Z TestFramework.node1 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-05T17:01:03.613000Z TestFramework.node1 (DEBUG): RPC successfully started\r\n2024-04-05T17:01:03.621000Z TestFramework.node2 (DEBUG): Stopping node\r\n2024-04-05T17:01:03.745000Z TestFramework.node2 (DEBUG): Node stopped\r\n2024-04-05T17:01:03.748000Z TestFramework.node2 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-05T17:01:04.009000Z TestFramework.node2 (DEBUG): RPC successfully started\r\n2024-04-05T17:01:04.311000Z TestFramework (INFO): make sure trying to access the indices throws errors\r\n2024-04-05T17:01:04.368000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-05T17:01:06.939000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-05T17:01:11.514000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-05T17:01:16.719000Z TestFramework (INFO): prune exactly up to the indices best blocks while the indices are disabled\r\n2024-04-05T17:01:16.757000Z TestFramework.node0 (DEBUG): Stopping node\r\n2024-04-05T17:01:16.987000Z TestFramework.node0 (DEBUG): Node stopped\r\n2024-04-05T17:01:16.991000Z TestFramework.node0 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-05T17:01:17.525000Z TestFramework.node0 (DEBUG): RPC successfully started\r\n2024-04-05T17:01:17.647000Z TestFramework.node1 (DEBUG): Stopping node\r\n2024-04-05T17:01:17.933000Z TestFramework.node1 (DEBUG): Node stopped\r\n2024-04-05T17:01:17.944000Z TestFramework.node1 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-05T17:01:18.733000Z TestFramework.node1 (DEBUG): RPC successfully started\r\n2024-04-05T17:01:18.785000Z TestFramework.node2 (DEBUG): Stopping node\r\n2024-04-05T17:01:19.015000Z TestFramework.node2 (DEBUG): Node stopped\r\n2024-04-05T17:01:19.020000Z TestFramework.node2 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-05T17:01:19.552000Z TestFramework.node2 (DEBUG): RPC successfully started\r\n2024-04-05T17:01:19.552000Z TestFramework (INFO): make sure that we can continue with the partially synced indices after having pruned up to the index height\r\n2024-04-05T17:01:24.744000Z TestFramework (INFO): prune further than the indices best blocks while the indices are disabled\r\n2024-04-05T17:01:24.745000Z TestFramework.node0 (DEBUG): Stopping node\r\n2024-04-05T17:01:24.913000Z TestFramework.node0 (DEBUG): Node stopped\r\n2024-04-05T17:01:24.919000Z TestFramework.node0 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-05T17:01:25.187000Z TestFramework.node0 (DEBUG): RPC successfully started\r\n2024-04-05T17:01:25.190000Z TestFramework.node1 (DEBUG): Stopping node\r\n2024-04-05T17:01:25.362000Z TestFramework.node1 (DEBUG): Node stopped\r\n2024-04-05T17:01:25.367000Z TestFramework.node1 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-05T17:01:26.173000Z TestFramework.node1 (DEBUG): RPC successfully started\r\n2024-04-05T17:01:26.173000Z TestFramework.node2 (DEBUG): Stopping node\r\n2024-04-05T17:01:26.345000Z TestFramework.node2 (DEBUG): Node stopped\r\n2024-04-05T17:01:26.347000Z TestFramework.node2 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-04-05T17:01:26.884000Z TestFramework.node2 (DEBUG): RPC successfully started\r\n2024-04-05T17:01:27.436000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-05T17:01:43.914000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-05T17:02:00.011000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-05T17:02:21.406000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`\r\n2024-04-05T17:02:51.411000Z TestFramework (ERROR): JSONRPC error\r\nTraceback (most recent call last):\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 151, in _get_response\r\n    http_response = self.__conn.getresponse()\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 1349, in getresponse\r\n    response.begin()\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 316, in begin\r\n    version, status, reason = self._read_status()\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 277, in _read_status\r\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py\", line 704, in readinto\r\n    return self._sock.recv_into(b)\r\nsocket.timeout: timed out\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/test_framework.py\", line 132, in main\r\n    self.run_test()\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/feature_index_prune.py\", line 121, in run_test\r\n    self.mine_batches(1000)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/feature_index_prune.py\", line 47, in mine_batches\r\n    self.generate(self.nodes[0], 250)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/test_framework.py\", line 695, in generate\r\n    blocks = generator.generate(*args, invalid_call=False, **kwargs)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/test_node.py\", line 333, in generate\r\n    return self.generatetoaddress(nblocks=nblocks, address=self.get_deterministic_priv_key().address, maxtries=maxtries, **kwargs)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/test_node.py\", line 341, in generatetoaddress\r\n    return self.__getattr__('generatetoaddress')(*args, **kwargs)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/coverage.py\", line 50, in __call__\r\n    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 127, in __call__\r\n    response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 106, in _request\r\n    return self._get_response()\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 153, in _get_response\r\n    raise JSONRPCException({\r\ntest_framework.authproxy.JSONRPCException: 'generatetoaddress' RPC took longer than 30.000000 seconds. Consider using larger timeout for calls that take longer to return. (-344)\r\n2024-04-05T17:02:51.444000Z TestFramework (DEBUG): Closing down network thread\r\n2024-04-05T17:02:51.521000Z TestFramework (INFO): Stopping nodes\r\n2024-04-05T17:02:51.548000Z TestFramework.node0 (DEBUG): Stopping node\r\n2024-04-05T17:02:51.575000Z TestFramework.node0 (ERROR): Unable to stop node.\r\nTraceback (most recent call last):\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/test_node.py\", line 375, in stop_node\r\n    self.stop(wait=wait)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/coverage.py\", line 50, in __call__\r\n    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 127, in __call__\r\n    response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))\r\n  File \"/Users/ioannis/Documents/projects/bitcoin/bitcoin/test/functional/test_framework/authproxy.py\", line 105, in _request\r\n    self.__conn.request(method, path, postdata, headers)\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 1257, in request\r\n    self._send_request(method, url, body, headers, encode_chunked)\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 1268, in _send_request\r\n    self.putrequest(method, url, **skips)\r\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 1094, in putrequest\r\n    raise CannotSendRequest(self.__state)\r\nhttp.client.CannotSendRequest: Request-sent\r\n2024-04-05T17:02:51.588000Z TestFramework.node1 (DEBUG): Stopping node\r\n2024-04-05T17:02:51.652000Z TestFramework.node2 (DEBUG): Stopping node\r\n2024-04-05T17:02:51.677000Z TestFramework.node3 (DEBUG): Stopping node\r\n2024-04-05T17:03:51.817000Z TestFramework.utils (ERROR): wait_until() failed. Predicate: ''''\r\n        self.wait_until(lambda: self.is_node_stopped(expected_ret_code=expected_ret_code, **kwargs), timeout=timeout)\r\n'''\r\n```\r\n\r\n</details>\r\n\r\n\r\n",
      "created_at" : "2024-04-06T17:28:10Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29791#issuecomment-2041145104",
      "id" : 2041145104,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29791",
      "node_id" : "IC_kwDOABII5855qWcQ",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2041145104/reactions"
      },
      "updated_at" : "2024-04-06T17:35:30Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2041145104",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/11520757?v=4",
         "events_url" : "https://api.github.com/users/itornaza/events{/privacy}",
         "followers_url" : "https://api.github.com/users/itornaza/followers",
         "following_url" : "https://api.github.com/users/itornaza/following{/other_user}",
         "gists_url" : "https://api.github.com/users/itornaza/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/itornaza",
         "id" : 11520757,
         "login" : "itornaza",
         "node_id" : "MDQ6VXNlcjExNTIwNzU3",
         "organizations_url" : "https://api.github.com/users/itornaza/orgs",
         "received_events_url" : "https://api.github.com/users/itornaza/received_events",
         "repos_url" : "https://api.github.com/users/itornaza/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/itornaza/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/itornaza/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/itornaza"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Out of frustration I took slightly different approach and run the functional tests with the support of a big enough ramdisk of 12 GiB inspired by the PR #29335 that was meant for a completely different use case. \r\n\r\nNot only all the extended tests pass on both the master and PR branches with 16 jobs and even 64 jobs but a 2x speed up is achieved down to 572 seconds. \r\n\r\nMy box has 96 GiB of unified memory so there is clearly some operating systems specifics that make the discussed tests to fail. Under the much smaller but more controlled environment of the ramdisk, everything runs smoothly. \r\n\r\nOn that note I would consider suggesting that the tests are advised to be run with a big enough ramdisk support in the [README.md](https://github.com/bitcoin/bitcoin/blob/master/test/) and at least for the mac users.",
      "created_at" : "2024-04-06T18:20:52Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29791#issuecomment-2041159007",
      "id" : 2041159007,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29791",
      "node_id" : "IC_kwDOABII5855qZ1f",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2041159007/reactions"
      },
      "updated_at" : "2024-04-06T18:53:05Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2041159007",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/11520757?v=4",
         "events_url" : "https://api.github.com/users/itornaza/events{/privacy}",
         "followers_url" : "https://api.github.com/users/itornaza/followers",
         "following_url" : "https://api.github.com/users/itornaza/following{/other_user}",
         "gists_url" : "https://api.github.com/users/itornaza/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/itornaza",
         "id" : 11520757,
         "login" : "itornaza",
         "node_id" : "MDQ6VXNlcjExNTIwNzU3",
         "organizations_url" : "https://api.github.com/users/itornaza/orgs",
         "received_events_url" : "https://api.github.com/users/itornaza/received_events",
         "repos_url" : "https://api.github.com/users/itornaza/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/itornaza/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/itornaza/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/itornaza"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "cc @m3dwards, as I think you had been seeing these timeouts as well.",
      "created_at" : "2024-04-07T09:38:50Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29791#issuecomment-2041390720",
      "id" : 2041390720,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29791",
      "node_id" : "IC_kwDOABII5855rSaA",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2041390720/reactions"
      },
      "updated_at" : "2024-04-07T09:38:50Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2041390720",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/863730?v=4",
         "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
         "followers_url" : "https://api.github.com/users/fanquake/followers",
         "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
         "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/fanquake",
         "id" : 863730,
         "login" : "fanquake",
         "node_id" : "MDQ6VXNlcjg2MzczMA==",
         "organizations_url" : "https://api.github.com/users/fanquake/orgs",
         "received_events_url" : "https://api.github.com/users/fanquake/received_events",
         "repos_url" : "https://api.github.com/users/fanquake/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/fanquake"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Happy for my first merged PR! :)\r\n\r\n## Post-merge post-mortem\r\n\r\n### Working stupidly, not smart or hard\r\n\r\nI have spent too many evenings focusing on this:\r\n> Agree that it might be fruitful to investigate the history of wallet_importdescriptors.py to pinpoint regressions, didn't have time today.\r\n\r\nIn over >110 runs, I have observed how the chance of `wallet_importdescriptors.py --descriptors` failure has increased with time. As patterns emerged around certain commits, I've tested further only to have the ratio of success/failure converge to around the same number before & after commits.\r\n\r\nIn hindsight, instead of hoping to get lucky in manually finding the offending commit, I should have been \"lazy\" and written an automated script to perform a larger number of runs to actually be able to get a large enough sample size to provide confidence. I think the threshold in `wallet_importdescriptors.py` changed by this PR is so close to the average runtime, that a really large sample size would be required. Maybe it's a case of death by a thousand cuts rather than a specific change.\r\n\r\n### Build configuration\r\n\r\nFor posterity, I was building with Clang 17.0.6, C & C++ compiler flags `-O0 -g`, `--with-debug` and `--with-gui=qt5` (yes, the last one is probably unnecessary in the context of this test). As optimizations are off and debugging is on it becomes more probably to see timeouts, but it's still good to be able to run tests in such a context.\r\n\r\n### Future directions\r\n\r\n* Implement/find tool for gathering statistical data on test failures over a range of commits.\r\n* Investigate why `feature_dbcrash.py` runs in ~45 minutes on my machine/build configuration while it takes something like 5 minutes on others.\r\n* Add build information into combined test logs.",
      "created_at" : "2024-04-08T12:38:38Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29791#issuecomment-2042641779",
      "id" : 2042641779,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29791",
      "node_id" : "IC_kwDOABII5855wD1z",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 1,
         "total_count" : 1,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2042641779/reactions"
      },
      "updated_at" : "2024-04-08T12:38:38Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2042641779",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/581308?v=4",
         "events_url" : "https://api.github.com/users/cbergqvist/events{/privacy}",
         "followers_url" : "https://api.github.com/users/cbergqvist/followers",
         "following_url" : "https://api.github.com/users/cbergqvist/following{/other_user}",
         "gists_url" : "https://api.github.com/users/cbergqvist/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/cbergqvist",
         "id" : 581308,
         "login" : "cbergqvist",
         "node_id" : "MDQ6VXNlcjU4MTMwOA==",
         "organizations_url" : "https://api.github.com/users/cbergqvist/orgs",
         "received_events_url" : "https://api.github.com/users/cbergqvist/received_events",
         "repos_url" : "https://api.github.com/users/cbergqvist/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/cbergqvist/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/cbergqvist/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/cbergqvist"
      }
   }
]
