{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "CONTRIBUTOR",
   "body" : "When the block index database is non-contiguous due to file corruption (i.e. it contains indexes of height `x-1` and `x+1`, but not `x`), bitcoind can currently crash with an assert in `BuildSkip()` / `GetAncestor()` during `BlockManager::LoadBlockIndex()`:\r\n```\r\nbitcoind: chain.cpp:112: const CBlockIndex* CBlockIndex::GetAncestor(int) const: Assertion `pindexWalk->pprev' failed.\r\n```\r\nThis PR changes it such that we instead return an `InitError` to the user.\r\n\r\nI stumbled upon this because I noticed that the file perturbation in `feature_init.py`  wasn't working as intended, which is fixed in the second commit:\r\n* Opening the file twice in one `with` statement would lead to `tf_read` being empty, so the test wouldn't perturb anything but replace the file with a new one. Fixed by first opening for read, then for write.\r\n* We need to restore the previous state after perturbations, so that only the current perturbation is active and not a mix of the current and previous ones.\r\n* I also added `checkblocks=200` to the startup parameters so that corruption in earlier blocks of `blk00000.dat` is detected during init verification and not ignored.\r\n\r\nAfter fixing `feature_init.py` like that I'd run into the `assert` mentioned above (so running the testfix from the second commit without the first one is a way to reproduce it).",
   "closed_at" : "2023-10-04T19:37:12Z",
   "closed_by" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/3782274?v=4",
      "events_url" : "https://api.github.com/users/achow101/events{/privacy}",
      "followers_url" : "https://api.github.com/users/achow101/followers",
      "following_url" : "https://api.github.com/users/achow101/following{/other_user}",
      "gists_url" : "https://api.github.com/users/achow101/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/achow101",
      "id" : 3782274,
      "login" : "achow101",
      "node_id" : "MDQ6VXNlcjM3ODIyNzQ=",
      "organizations_url" : "https://api.github.com/users/achow101/orgs",
      "received_events_url" : "https://api.github.com/users/achow101/received_events",
      "repos_url" : "https://api.github.com/users/achow101/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/achow101/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/achow101/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/achow101"
   },
   "comments" : 8,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/27823/comments",
   "created_at" : "2023-06-04T18:55:13Z",
   "draft" : false,
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/27823/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/pull/27823",
   "id" : 1740531376,
   "labels" : [],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/27823/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "PR_kwDOABII585SIOMw",
   "number" : 27823,
   "performed_via_github_app" : null,
   "pull_request" : {
      "diff_url" : "https://github.com/bitcoin/bitcoin/pull/27823.diff",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/27823",
      "merged_at" : "2023-10-04T19:37:12Z",
      "patch_url" : "https://github.com/bitcoin/bitcoin/pull/27823.patch",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/27823"
   },
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/27823/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "state_reason" : null,
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/27823/timeline",
   "title" : "init: return error when block index is non-contiguous, fix feature_init.py file perturbation",
   "updated_at" : "2023-10-04T19:37:12Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/27823",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/48763452?v=4",
      "events_url" : "https://api.github.com/users/mzumsande/events{/privacy}",
      "followers_url" : "https://api.github.com/users/mzumsande/followers",
      "following_url" : "https://api.github.com/users/mzumsande/following{/other_user}",
      "gists_url" : "https://api.github.com/users/mzumsande/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/mzumsande",
      "id" : 48763452,
      "login" : "mzumsande",
      "node_id" : "MDQ6VXNlcjQ4NzYzNDUy",
      "organizations_url" : "https://api.github.com/users/mzumsande/orgs",
      "received_events_url" : "https://api.github.com/users/mzumsande/received_events",
      "repos_url" : "https://api.github.com/users/mzumsande/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/mzumsande/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/mzumsande/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/mzumsande"
   }
}
